"""empty message

Revision ID: 0e8c346114d9
Revises: bf6c138d057f
Create Date: 2025-06-22 03:32:08.432261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e8c346114d9'
down_revision = 'bf6c138d057f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('load',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broker_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_year', sa.String(length=120), nullable=False),
    sa.Column('vehicle_make', sa.String(length=120), nullable=False),
    sa.Column('vehicle_model', sa.String(length=120), nullable=False),
    sa.Column('pickup_location', sa.String(length=120), nullable=False),
    sa.Column('delivery_location', sa.String(length=120), nullable=False),
    sa.Column('payment', sa.Float(), nullable=False),
    sa.Column('days_to_deliver', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=120), nullable=False),
    sa.Column('carrier_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['broker_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['carrier_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('load_requests',
    sa.Column('carrier_id', sa.Integer(), nullable=False),
    sa.Column('load_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['load_id'], ['load.id'], ),
    sa.PrimaryKeyConstraint('carrier_id', 'load_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('load_requests')
    op.drop_table('load')
    # ### end Alembic commands ###
