"""empty message

Revision ID: 5333c38efbc1
Revises: fd7d9ff99e47
Create Date: 2025-07-31 01:22:16.723276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5333c38efbc1'
down_revision = 'fd7d9ff99e47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###
