"""empty message

Revision ID: 556ec3626825
Revises: 5333c38efbc1
Create Date: 2025-07-31 01:31:35.779038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '556ec3626825'
down_revision = '5333c38efbc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_company_name_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('user_company_name_key'), ['company_name'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
