"""empty message

Revision ID: 86e897a1ea26
Revises: 0e8c346114d9
Create Date: 2025-06-22 04:25:12.512832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86e897a1ea26'
down_revision = '0e8c346114d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('load_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carrier_id', sa.Integer(), nullable=False),
    sa.Column('load_id', sa.Integer(), nullable=False),
    sa.Column('vehicle', sa.String(length=120), nullable=False),
    sa.Column('price_offer', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['carrier_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['load_id'], ['load.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('load_requests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('load_requests',
    sa.Column('carrier_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('load_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['user.id'], name='load_requests_carrier_id_fkey'),
    sa.ForeignKeyConstraint(['load_id'], ['load.id'], name='load_requests_load_id_fkey'),
    sa.PrimaryKeyConstraint('carrier_id', 'load_id', name='load_requests_pkey')
    )
    op.drop_table('load_request')
    # ### end Alembic commands ###
