"""empty message

Revision ID: bf6c138d057f
Revises: 0763d677d453
Create Date: 2025-06-21 04:45:49.627157

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bf6c138d057f'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    roles_enum = postgresql.ENUM('broker', 'carrier', name='roles')
    roles_enum.create(op.get_bind(), checkfirst=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('company_name', sa.String(length=120), nullable=False))
        batch_op.add_column(
            sa.Column('full_name', sa.String(length=120), nullable=False))
        batch_op.add_column(
            sa.Column('phone_number', sa.String(length=15), nullable=False))
        batch_op.add_column(
            sa.Column('address', sa.String(length=120), nullable=False))
        batch_op.add_column(
            sa.Column('city', sa.String(length=120), nullable=False))
        batch_op.add_column(
            sa.Column('state', sa.String(length=120), nullable=False))
        batch_op.add_column(
            sa.Column('zip', sa.String(length=120), nullable=False))
        batch_op.add_column(
            sa.Column('mc_number', sa.String(length=120), nullable=False))
        batch_op.add_column(
            sa.Column('usdot_number', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('type_of_transport',
                            sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('number_of_trucks',
                            sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('role', sa.Enum(
            'BROKER', 'CARRIER', name='roles'), nullable=False))
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=False))
        batch_op.add_column(
            sa.Column('password_hash', sa.String(length=300), nullable=False))
        batch_op.create_unique_constraint(None, ['usdot_number'])
        batch_op.create_unique_constraint(None, ['company_name'])
        batch_op.create_unique_constraint(None, ['mc_number'])
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    roles_enum = postgresql.ENUM('broker', 'carrier', name='roles')
    roles_enum.drop(op.get_bind(), checkfirst=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('rating')
        batch_op.drop_column('role')
        batch_op.drop_column('number_of_trucks')
        batch_op.drop_column('type_of_transport')
        batch_op.drop_column('usdot_number')
        batch_op.drop_column('mc_number')
        batch_op.drop_column('zip')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('address')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('full_name')
        batch_op.drop_column('company_name')

    # ### end Alembic commands ###
