"""empty message

Revision ID: d5b16250efe3
Revises: ec3e9f12603a
Create Date: 2025-06-22 20:02:53.644055

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd5b16250efe3'
down_revision = 'ec3e9f12603a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Enum('BROKER', 'CARRIER', name='roles'), nullable=False))
        batch_op.drop_column('role_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_type', postgresql.ENUM('broker', 'carrier', name='roles'), autoincrement=False, nullable=False))
        batch_op.drop_column('role')

    # ### end Alembic commands ###
