"""empty message

Revision ID: ec3e9f12603a
Revises: b5193b1e4b41
Create Date: 2025-06-22 19:52:24.623484

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision = 'ec3e9f12603a'
down_revision = 'b5193b1e4b41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=120), nullable=False),
                    sa.Column('role_type', ENUM('BROKER', 'CARRIER',
                                                name='roles', create_type=False), nullable=False),
                    sa.Column('price', sa.Float(), nullable=False),
                    sa.Column('currency', sa.String(
                        length=120), nullable=False),
                    sa.Column('description', sa.Text(), nullable=False),
                    sa.Column('max_screens', sa.Integer(), nullable=False),
                    sa.Column('can_view_loads', sa.Boolean(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'plan', ['plan_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('plan_id')

    op.drop_table('plan')
    # ### end Alembic commands ###
