"""empty message

Revision ID: f3617d9f793b
Revises: 
Create Date: 2025-07-08 02:15:01.798722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3617d9f793b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('carrier', 'broker', 'admin', name='roles'), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('max_screens', sa.Integer(), nullable=False),
    sa.Column('can_view_loads', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=120), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('zip', sa.String(length=120), nullable=False),
    sa.Column('mc_number', sa.String(length=120), nullable=False),
    sa.Column('usdot_number', sa.String(length=120), nullable=True),
    sa.Column('type_of_transport', sa.String(length=120), nullable=True),
    sa.Column('number_of_trucks', sa.Integer(), nullable=True),
    sa.Column('role', sa.Enum('carrier', 'broker', 'admin', name='roles'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_name'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mc_number'),
    sa.UniqueConstraint('usdot_number')
    )
    op.create_table('load',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broker_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_year', sa.String(length=120), nullable=False),
    sa.Column('vehicle_make', sa.String(length=120), nullable=False),
    sa.Column('vehicle_model', sa.String(length=120), nullable=False),
    sa.Column('pickup_location', sa.String(length=120), nullable=False),
    sa.Column('delivery_location', sa.String(length=120), nullable=False),
    sa.Column('payment', sa.Float(), nullable=False),
    sa.Column('days_to_deliver', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=120), nullable=False),
    sa.Column('carrier_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['broker_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['carrier_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=120), nullable=False),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('load_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carrier_id', sa.Integer(), nullable=False),
    sa.Column('load_id', sa.Integer(), nullable=False),
    sa.Column('vehicle', sa.String(length=120), nullable=True),
    sa.Column('price_offer', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['carrier_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['load_id'], ['load.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=120), nullable=False),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=120), nullable=False),
    sa.Column('payment_method', sa.String(length=120), nullable=False),
    sa.Column('transaction_id_gateway', sa.String(length=120), nullable=False),
    sa.Column('next_retry_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_transaction')
    op.drop_table('load_request')
    op.drop_table('subscription')
    op.drop_table('load')
    op.drop_table('user')
    op.drop_table('plan')
    # ### end Alembic commands ###
