"""empty message

Revision ID: fd7d9ff99e47
Revises: 94e4a98998b6
Create Date: 2025-07-25 12:12:30.326228

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fd7d9ff99e47'
down_revision = '94e4a98998b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('zip',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('mc_number',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('carrier', 'broker', 'admin', name='roles'),
               nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('carrier', 'broker', 'admin', name='roles'),
               nullable=False)
        batch_op.alter_column('mc_number',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('zip',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)

    # ### end Alembic commands ###
